name: chatflow_3
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.9.0
<<<<<<< HEAD
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.16.0
=======
  image_picker: ^1.0.7
>>>>>>> 829215fd42ac0e09149a8f2b0cbf5872f6d068cc

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
