name: chatflow_3
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.9.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  http: ^1.1.0
  
  # Thư viện Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.5

  # Thư viện Cờ Vua (Theo gợi ý của hệ thống)
  flutter_chess_board: ^1.0.1
  record: ^6.2.0
  audioplayers: ^6.6.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
