name: chatflow_3
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+2
  path: ^1.9.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  intl: ^0.19.0
  http: ^1.2.2
  googleapis_auth: ^1.4.1 

  # Firebase & Notifications
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.0.0

  # Plugins & Games
  flutter_chess_board: ^1.0.1
  record: 5.1.0
  audioplayers: ^6.1.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Loại bỏ hoàn toàn các overrides cũ để pub tự tìm bản khớp với record 5.1.0
dependency_overrides:
  record_linux: 1.1.0
  record_platform_interface: 1.4.0

flutter:
  uses-material-design: true
  assets:
    # - lib/feature/assets/service-account.json # Tạm thời ẩn đi vì thiếu file thực tế
